#!/usr/bin/env python
import random
import sys
import os

try:
	amount = int(sys.argv[1])
except IndexError:
	print "value greater than 1 required"
	exit(0)

f = open('/usr/share/dict/words')

words = map(lambda x: x.strip(), f.readlines())

selected = []

for i in range(amount):
	selected += [random.choice(words)]

for i in range(amount):
	selected[i]+=str(random.randint(1,999999999))

password = '-'.join( selected ).capitalize()

print password